spring.datasource.url=jdbc:postgresql://localhost:5432/colatail
spring.datasource.username=colatail_user
spring.datasource.password=colatail123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false
